export const SET_ERRORS = 'SET_ERRORS';
export const IS_FETCHING_COMMENTS = 'IS_FETCHING_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const UNDO_REMOVE_COMMENT = 'UNDO_REMOVE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
